import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.8.0"
//    java
}
/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.6/samples
 * This project uses @Incubating APIs which are subject to change.
 */


version = "0.1.0"


allprojects {
    repositories {
        maven("https://plugins.gradle.org/m2/")
        gradlePluginPortal()
    }
}
dependencies {
    implementation(kotlin("stdlib-jdk8"))
}
repositories {
    mavenCentral()
    gradlePluginPortal()
}
//val compileKotlin: KotlinCompile by tasks
//compileKotlin.kotlinOptions {
//    jvmTarget = "1.8"
//}
//val compileTestKotlin: KotlinCompile by tasks
//compileTestKotlin.kotlinOptions {
//    jvmTarget = "1.8"
//}
subprojects {
    val sourceJar by tasks.registering(Jar::class) {
        archiveClassifier.set("sources")
        from(sourceSets["main"].allSource)
    }
    val testJar by tasks.registering(Jar::class) {
        archiveClassifier.set("test")
        from(sourceSets["test"].output)
    }

//    tasks {
//        withType<Copy> {
//            duplicatesStrategy = DuplicatesStrategy.WARN
//        }
//        withType<Jar> {
//            duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//        }
//    }
}